#UPDATE PARAMS
model_directory: /home/mark/audio_learning_project/vibrotactile_localization/learning/outputs/2D_full_dataset_working



# ----- mic / data param -----
data_dir: /home/mark/audio_learning_project/data/franka_2D_localization_full/ #franka_2D_localization
background_dir: /home/mark/audio_learning_project/data/franka_constant/trial0/

transform: mel

device_list: [2,10,11,12,13,14]
augment_device_list_used: [2,10,11,12,13,14]

max_num_frames: 88200

sample_rate: 44100
n_fft: 512
hop_length: 128
n_mels: 50
resample_rate: 11025

batch_size: 16
val_batch_size: 16

log_wandb: False
visuaize_regression: False
visuaize_dataset: False # to visualize the dataloader 


# ----- preprocessing parameters -----
subtract_background: False # ***** key parameter *****

# ----- mic augmentation param -----
normalize_audio_data: False

# ----- output representation parameters -----

output_representation:  'xy' #'height' #'xy' #'radian' 
output_representation_normalize: False #for ablation study, to normalize the output representation

# -----  augmentation param -----
augment_timeshift: False # ***** key parameter ***** (upon init dataset)
affine_transform: False
augment_timemask: False #upon getitem in dataloader
augment_freqmask: False #upon getitem in dataloader

