#UPDATE PARAMS
# model_directory: /home/mark/audio_learning_project/vibrotactile_localization/learning/outputs/wood_T12_T22_T25_T32_L42_T22_L80_Horizontal_combined_model
model_directory: /home/mark/audio_learning_project/vibrotactile_localization/learning/outputs/UMC_NO_normv2 #v2_v3data_Multi_ResNet50_MLP_selfattn_audio_gcc #v2_v3data_Multi_ResNet50_MLP_selfattn_audio_state_gcc  #resnet_b256_lr1e3 #wood_T12_T22_T25_T32_L42_T22_L80_Horizontal_combinedv2_suction_model

#proprio: v2_v3_data_Multi_ResNet50_MLP_xt_xdot_only_nopos
#audio: resnet_b256_lr1e3
#audio + proprio: v2_v3_data_Multi_ResNet50_MLP_xt_xdot
#audio + phase: v2_v3data_Multi_ResNet50_MLP_selfattn_audio_gcc
#audio + proprio + phase: v2_v3data_Multi_ResNet50_MLP_selfattn_audio_state_gcc

#ablation pre-processing: UMC_everything, UMC_nothing

# ----- mic / data param -----
data_dir:  #DOESNT MATTER BC IN EVAL.py #franka_2D_localization
background_dir: /home/mark/audio_learning_project/data/franka_constant/no_contact/trial0/

transform: mel

device_list: [2]
num_channel: 6
max_num_frames: 88200 #2 sec duration during data collection

window_frame: 66150 #[44100 for 1 sec for input_spectrogram_bins = 138], [66150 for 1.5 sec for input_spectrogram_bins = 345] 
CNN_layer_size: 4864 #[torch.nn.Linear(1536,512) for 0.2 second input],[#torch.nn.Linear(4864,512) for 1.0 second input]
sample_rate: 44100
n_fft: 512
hop_length: 128
input_spectrogram_bins: 345 #[138 for 0.2s duration for NFFT512, HOP 64], [345 for 1s duration for NFFT512, HOP 128]
n_mels: 50
resample_rate: 11025


batch_size: 1
val_batch_size: 1


# ----- preprocessing parameters -----
subtract_background: True # ***** key parameter *****
normalize_audio_data: False # ***** key parameter *****

load_meanvar_output: True

# ----- augmentation param -----
augment_data: True #for general _getitem_ modification enable/disable
augment_timeshift: True # ***** key parameter ***** (upon init dataset)
affine_transform: True
augment_timemask: True #upon getitem in dataloader
augment_freqmask: True #upon getitem in dataloader



# ----- output representation parameters -----

output_representation:  'xy' #'height' #'xy' #'radian' 
output_representation_normalize: False #for ablation study, to normalize the output representation


# -------- debugging --------
save_meanvar_output: False

# ----- visualization parameters -----
inspect_data_label: False # to iteratively visualize the audio & GT label in 3D plot 
visualize_subtract_background: False
visuaize_dataset: False # to visualize the dataloader
visuaize_regression: False # for evaluation, to visualize the regression output 

cylinder_radius: 0.06 #in meters