#UPDATE PARAMS
model_directory: /home/mark/audio_learning_project/vibrotactile_localization/learning/outputs/v3data_Multi_ResNet50_MLP_selfattn_xt_xdot_gcc #resnet50_qt_mini_dropout #resnet50_qt_mini_dropout #wood_suctionOnly_horizontal_opposite_verticalv2 #resnet_b256_lr1e3 #wood_suctionOnly_horizontal_opposite_verticalv2



# ----- mic / data param -----
background_dir: /home/mark/audio_learning_project/data/franka_constant/no_contact/trial0/
data_dir: /home/mark/audio_learning_project/data/test_mapping/cross_easy_full_new_v4/ #cross_easy_fullv2/ #cross_easy_uniformexplore_v2/ #cross_easy_fullv2/ #test_generalization/cross_easy_X_15_Left/ #test_mapping/cross_easy_fullv2/
transform: mel

device_list: [2]
num_channel: 6
max_num_frames: 88200 #2 sec duration during data collection

window_frame: 66150 #[44100 for 1 sec for input_spectrogram_bins = 138], [66150 for 1.5 sec for input_spectrogram_bins = 345] 
CNN_layer_size: 4864 #[torch.nn.Linear(1536,512) for 0.2 second input],[#torch.nn.Linear(4864,512) for 1.0 second input]
sample_rate: 44100
n_fft: 512
hop_length: 128
input_spectrogram_bins: 345 #[138 for 0.2s duration for NFFT512, HOP 64], [345 for 1s duration for NFFT512, HOP 128]
n_mels: 50
resample_rate: 11025


batch_size: 100
val_batch_size: 100


# ----- preprocessing parameters -----
subtract_background: True # ***** key parameter *****
normalize_audio_data: True # ***** key parameter *****

load_meanvar_output: True

# ----- augmentation param -----
augment_data: True #for general _getitem_ modification enable/disable
augment_timeshift: True # ***** key parameter ***** (upon init dataset)
affine_transform: True
augment_timemask: False #upon getitem in dataloader
augment_freqmask: False #upon getitem in dataloader



# ----- output representation parameters -----

output_representation:  'xy' #'height' #'xy' #'radian' 
output_representation_normalize: False #for ablation study, to normalize the output representation


# -------- debugging --------
save_meanvar_output: False

# ----- visualization parameters -----
inspect_data_label: False # to iteratively visualize the audio & GT label in 3D plot 
visualize_subtract_background: False
visuaize_dataset: True # to visualize the dataloader
visuaize_regression: True # for evaluation, to visualize the regression output 


# ----- Hardware specific parameters for vis -----
cylinder_radius: 0.06 #in meters
cylinder_origin_offset: 0.055 #in meters
cylinder_predict_z_range: 0.2032 #in meters

cylinder_transform_offset: 50 #in degrees. Dataset collection offset from when j7=0 to contact pt in angle. 