# ----- wandb log parameters -----
log_wandb: False
wandb_run_name: "baseline_6mic_preprocess"
wandb_project: "audio_localization3"


data_dir: /home/mark/audio_learning_project/data/franka_init_test_6mic/ #franka_2D_1line/
background_dir: /home/mark/audio_learning_project/data/franka_constant/trial0/
transform: mel

device_list: [0,1,11,12,13,14] #[9,10,11,12,13,14]
max_num_frames: 88200 #2 sec duration during data collection

sample_rate: 44100
n_fft: 512
hop_length: 128
n_mels: 40
resample_rate: 11025

# ----- preprocessing parameters -----
subtract_background: True # ***** key parameter *****
bandpass_filter: ???

# ----- visualization parameters -----
visuaize_dataset: False
visuaize_regression: True

# ----- training parameters -----

model_path: /home/mark/audio_learning_project/models
normalize_audio_data: False # ***** key parameter *****
checkpoint_dir: ???

batch_size: 16
val_batch_size: 16

# ----- augmentation param -----
augment_timeshift: True # ***** key parameter ***** (upon init dataset)
augment_timemask: False
augment_freqmask: False

# ----- training hypertuning parameters -----
train_epochs: 400
log_frequency: 10
eval_frequency: 10



