# ----- wandb log parameters -----
log_wandb: False
wandb_run_name: "UMC_centered_NO_time,sub"
wandb_project: "audio_localization6"


data_dir: /home/mark/audio_learning_project/data/franka_2D_localization_full_UMC/ #franka_2D_localization/ #franka_2D_1line
background_dir: /home/mark/audio_learning_project/data/franka_constant/background_noise/trial0/
transform: mel

device_list: [2]
num_channel: 6
max_num_frames: 88200 #2 sec duration during data collection
window_frame: 44100

sample_rate: 44100
n_fft: 512
hop_length: 128
n_mels: 50
resample_rate: 11025

# ----- preprocessing parameters -----
subtract_background: False # ***** key parameter *****
normalize_audio_data: True # ***** key parameter *****


# ----- augmentation param -----
augment_data: True #for general _getitem_ modification enable/disable
augment_timeshift: False # ***** key parameter ***** (upon init dataset)
affine_transform: False
augment_timemask: True #upon getitem in dataloader
augment_freqmask: True #upon getitem in dataloader


# ----- training parameters -----

model_path: /home/mark/audio_learning_project/models
checkpoint_dir: ??? #to be filled in by hydra

batch_size: 16
val_batch_size: 16

# ----- output representation parameters -----
output_representation: 'xy' #'height_radianclass' #'height' #'xy' #'radian' 
output_representation_normalize: False #for ablation study, to normalize the output representation


# ----- training hypertuning parameters -----
train_epochs: 200 #400
log_frequency: 1
eval_frequency: 1


# ----- visualization parameters -----
inspect_data_label: False # to iteratively visualize the audio & GT label in 3D plot 
visualize_subtract_background: False
visuaize_dataset: False # to visualize the dataloader
visuaize_regression: True # for evaluation, to visualize the regression output 

# -------- debugging --------

save_meanvar_output: False