# ----- wandb log parameters -----
log_wandb: True
wandb_run_name: "6mic_normalize_aug_valnoaug"
wandb_project: "audio_localization2"


data_dir: /home/mark/audio_learning_project/data/franka_init_test_6mic/
transform: mel

device_list: [0,1,11,12,13,14]
max_num_frames: 44100

sample_rate: 44100
n_fft: 512
hop_length: 128
n_mels: 40
resample_rate: 11025
trim_duration: 0.5

# ----- visualization parameters -----
visuaize_dataset: False
visuaize_regression: True

# ----- training parameters -----

model_path: /home/mark/audio_learning_project/models
normalize_audio_data: True
checkpoint_dir: ???

# ----- augmentation param -----
augment_audio: True #True when doing ablation study
augment_num_channel: 6
augment_device_list_used: [0,1,11,12,13,14]

augment_timeshift: False #manually shifting dataset upon init

apply_augmentation: True #automatically apply augmentation during training
augmentation_type: time_shift

# ----- training hypertuning parameters -----
train_epochs: 400
log_frequency: 10
eval_frequency: 10

batch_size: 16
val_batch_size: 16

